export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import  Footer from '../components/footer';
import Header from '../components/header';
import Navbar from '@/components/navbar';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      
      <body>
      <Header />
      <Navbar />
        {children}

        <Footer /> 
      </body>
      
      
    </html>
  )
}
